
name: Synopsys - Actions

on:
  workflow_dispatch

jobs:
  Synopsys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Polaris Scan (SAST)
        uses: synopsys-sig/synopsys-action@v1.2.0
        with:
          polaris_serverUrl: ${{ secrets.BRIDGE_POLARIS_SERVERURL }}
          polaris_accessToken: ${{ secrets.BRIDGE_POLARIS_ACCESSTOKEN }}
          polaris_application_name: "TestProjects"
          polaris_project_name: ${{ github.event.repository.name }}
          polaris_assessment_types: "SAST"            
          
      - name: Black Duck Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.2.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_PROJECT_VERSION_PHASE: "RELEASED"          
        with:
          blackduck_url: ${{ secrets.BD_URL }}
          blackduck_apiToken: ${{ secrets.BD_TOKEN }}
          blackduck_scan_full: true
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'

      - name: Black Duck PR Scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: synopsys-sig/synopsys-action@v1.2.0
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_PROJECT_VERSION_PHASE: "RELEASED" 
        with:
          blackduck_url: ${{ secrets.BD_URL }}
          blackduck_apiToken: ${{ secrets.BD_TOKEN }}
          blackduck_scan_full: false
          blackduck_automation_prcomment: true
          github_token: ${{ secrets.GH_TOKEN }}
